FIRMonitoringSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('fir/', include('fir.urls')),
    path('firBeta/', include('firBeta.urls')),
    path('fault/<str:fault>/', views.fault, name='fault'),
    path('success/<str:msg>/', views.success, name='success'),
    path('send_mails_for_the_day/', views.send_mails_for_the_day, name='send_mails_for_the_day'),
    # path('populate/', views.populate, name='populate'),
    # path('delete/', views.delete, name='delete'),
    # path('change_passwords/', views.change_passwords, name='change_passwords'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

fir/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'fir'

urlpatterns = [

    # Police Station
    path('create_fir/', views.create_fir_view, name='create_fir'),
    path('update_fir_ps/<int:pk>', views.update_fir_police_station_view, name='update_fir_police_station'),
    path('add_new_phase/<int:pk>', views.add_new_phase_view, name='add_new_phase'),
    path('list_firs_police_station/', views.list_firs_police_station_view, name='list_firs_police_station'),

    
    # Court
    # path('update_fir_court/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_court_view, name='update_fir_court'),
    path('update_fir_court/<int:pk>/', views.update_fir_court_view, name='update_fir_court'),
    path('list_firs_court/', views.list_firs_court_view, name='list_firs_court'),
    # path('list_firs_court/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_court_with_param_view, name='list_firs_court_with_param'),


    # DSP
    path('list_firs_dsp/', views.list_firs_dsp_view, name='list_firs_dsp'),


    # VRK
    path('update_fir_vrk/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_vrk_view, name='update_fir_vrk'),
    path('list_firs_vrk/', views.list_firs_vrk_view, name='list_firs_vrk'),
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('list_firs_vrk/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_vrk_with_param_view, name='list_firs_vrk_with_param'),


    # SSP
    path('update_fir_ssp/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_ssp_view, name='update_fir_ssp'),
    path('list_firs_ssp/', views.list_firs_ssp_view, name='list_firs_ssp'),
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('list_firs_ssp/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_ssp_with_param_view, name='list_firs_ssp_with_param'),

    # Monitoring
    path('', views.filter_data_view, name='filter_fir_data'),
    path('detail/<int:pk>', views.detail_fir_view, name='detail_fir'),
]

fir/models.py
from django.db import models

# Create your models here.


class FIR(models.Model):

    PHASE_CHOICES=[(1,1),(2,2),(3,3)]
    ACCUSED_STATUS_CHOICES = [('arrested','Arrested'),('not_arrested','Not Arrested'),('po','PO')]
    CURRENT_STATUS_CHOICES = [('under_investigation','Under Investigation'),('challan_filed','Challan Filed'),('untraced','Untraced'),('cancelled','Cancelled')]
    COURT_STATUS_CHOICES = [('pending','Pending'),('accepted','Accepted'),('reinvestigation','Reinvestigation')]

    sub_division = models.ForeignKey("location.SubDivision", related_name='firs', on_delete=models.CASCADE)
    police_station = models.ForeignKey("location.PoliceStation", related_name='firs', on_delete=models.CASCADE)

    fir_no = models.CharField(max_length=50)
    phase = models.PositiveIntegerField(choices=PHASE_CHOICES)
    date_created = models.DateField()
    date_created_on_system = models.DateField(auto_now_add=True)

    io_name = models.CharField(max_length=50, blank=True, null=True)
    accused_name = models.TextField(blank=True, null=True)
    under_section = models.CharField(max_length=50, blank=True, null=True)
    accused_status = models.CharField(max_length=50, choices=ACCUSED_STATUS_CHOICES, blank=True, null=True)
    limitation_period = models.PositiveIntegerField(blank=True, null=True)
    
    current_status = models.CharField(max_length=50, choices=CURRENT_STATUS_CHOICES, blank=True, null=True)
    put_in_ssp_office = models.BooleanField(default=False)
    put_in_ssp_office_date = models.DateField(blank=True, null=True)
    ssp_approved = models.BooleanField(default=False)

    put_in_court = models.BooleanField(default=False)
    put_in_court_date = models.DateField(blank=True, null=True)

    received_in_court = models.BooleanField(default=False)
    received_in_court_date = models.DateField(blank=True, null=True)
    court_status = models.CharField(max_length=50, choices=COURT_STATUS_CHOICES, blank=True,  null=True)
    reverted_by_court_date = models.DateField(blank=True,  null=True)

    received_from_court_date = models.DateField(blank=True,  null=True)
    appointed_io = models.CharField(max_length=50, blank=True,  null=True)

    is_closed = models.BooleanField(default=False)
    closed_date = models.DateField(blank=True, null=True)


    def __str__(self):
        return f'{self.sub_division} - {self.police_station} - {self.fir_no} - {self.phase}'

    class Meta():
        unique_together = ['sub_division', 'police_station', 'fir_no', 'phase']
        ordering = ['sub_division', 'police_station', '-fir_no', 'phase']
        verbose_name = 'FIR'
        verbose_name_plural = 'FIRs'   

location/models.py
from django.db import models

# Create your models here.


class SubDivision(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class PoliceStation(models.Model):
    sub_division = models.ForeignKey("location.SubDivision", related_name='police_stations',on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    

fir/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.db.models import F
import datetime

from location import models as loc_models
from account import models as acc_models
from . import models, forms, filters
# Create your views here.

get_request_dict = {
    'fir_no': 'FIR No',
    'date_created__gte': 'Date Registered (Lower Limit)',
    'date_created__lte': 'Date Registered (Upper Limit)',
    'io_name__contains': 'IO Name',
    'accused_name__contains': 'Accused Name',
    'under_section__contains': 'Under Section',
    'accused_status': 'Accused Status',
    'limitation_period__gte': 'Limitation Period (Lower Limit)',
    'limitation_period__lte': 'Limitation Period (Upper Limit)',
    'days_to_expire__gte': 'Days to Expire (Lower Limit)',
    'days_to_expire__lte': 'Days to Expire (Upper Limit)',
    'current_status': 'Current Status',
    'put_in_ssp_office': 'Submitted to SSP Office',
    'put_in_ssp_office_date__gte': 'Date of Submission in SSP Office (Lower Limit)',
    'put_in_ssp_office_date__lte': 'Date of Submission in SSP Office (Upper Limit)',
    'ssp_approved': 'SSP Approved',
    'put_in_court': 'Submitted in Court',
    'put_in_court_date__gte': 'Date of Submission in Court (Lower Limit)',
    'put_in_court_date__lte': 'Date of Submission in Court (Upper Limit)',
    'received_in_court': 'Received in Court',
    'received_in_court_date__gte': 'Date of Receiving in Court (Lower Limit)' ,
    'received_in_court_date__lte': 'Date of Receiving in Court (Upper Limit)' ,
    'court_status': 'Court Status' ,
    'reverted_by_court_date__gte': 'Date of reverting from Court (Lower Limit)' ,
    'reverted_by_court_date__lte': 'Date of reverting from Court (Upper Limit)' ,
    'received_from_court_date__gte': 'Date of receiving in Police Station (Lower Limit)' ,
    'received_from_court_date__lte': 'Date of receiving in Police Station (Upper Limit)' ,
    'appointed_io__contains': 'Appointed IO Name',
    'is_closed': 'Closed FIR'
}

@login_required
def create_fir_view(request):

    police_station_record_keepers = [u['user'] for u in acc_models.PoliceStationRecordKeeper.objects.all().values('user')]

    if request.user.pk in police_station_record_keepers:
        if request.method == 'POST':
            form = forms.CreateFIRForm(request.POST)
            if form.is_valid():
                fir = form.save(commit=False)
                fir.phase = 1
                ps_record_keeper = acc_models.PoliceStationRecordKeeper.objects.get(user__pk__exact=request.user.pk)
                fir.sub_division = ps_record_keeper.sub_division 
                fir.police_station = ps_record_keeper.police_station
                try:
                    fir.save()
                except:
                    return redirect('fault', fault='Invalid Input parameters!\nPossible repetition of FIR Number, kindly verify')
                return redirect('fir:list_firs_police_station')
            else:
                return redirect('fault', fault='Input parameters of Create FIR Form are not valid')
        else:
            form = forms.CreateFIRForm()
            return render(request, 'fir/create_fir.html', {'form':form})
    else:
        return redirect('fault', fault='ACCESS DENIED!')


@login_required
def update_fir_police_station_view(request, pk):

    police_station_record_keepers = [u['user'] for u in acc_models.PoliceStationRecordKeeper.objects.all().values('user')]

    prev_path = request.META.get('HTTP_REFERER', '/')
    current_path = request.path
    if prev_path == '/':
        response = '/'
        request.session['response_to_redirect'] = response
    elif not current_path in prev_path:
        response = prev_path
        request.session['response_to_redirect'] = response

    if (request.user.pk in police_station_record_keepers) and (acc_models.PoliceStationRecordKeeper.objects.get(user__pk__exact=request.user.pk).police_station == models.FIR.objects.get(pk__exact=pk).police_station) :
        if request.method == 'POST':
            form = forms.UpdateFIRPoliceStationForm(request.POST)
            if form.is_valid():
                fir = models.FIR.objects.get(pk__exact=pk)
                fir.io_name = form.cleaned_data['io_name']
                fir.accused_name = form.cleaned_data['accused_name']
                fir.under_section = form.cleaned_data['under_section']
                fir.accused_status = form.cleaned_data['accused_status']
                fir.limitation_period = form.cleaned_data['limitation_period']
                fir.current_status = form.cleaned_data['current_status']
                fir.put_in_ssp_office = form.cleaned_data['put_in_ssp_office']
                fir.put_in_ssp_office_date = form.cleaned_data['put_in_ssp_office_date']
                fir.put_in_court = form.cleaned_data['put_in_court']
                fir.put_in_court_date = form.cleaned_data['put_in_court_date']
                fir.received_from_court_date = form.cleaned_data['received_from_court_date']
                fir.appointed_io = form.cleaned_data['appointed_io']
                fir.is_closed = form.cleaned_data['is_closed']
                fir.closed_date = form.cleaned_data['closed_date']
                fir.save()

                if(fir.is_closed):
                    fir_list = models.FIR.objects.all().filter(fir_no__exact=fir.fir_no, police_station__exact=fir.police_station, sub_division__exact=fir.sub_division)
                    for f in fir_list:
                        f.is_closed = True
                        f.closed_date = fir.closed_date
                        f.save()

                response = request.session.get('response_to_redirect', None)
                if response and response != '/':
                    return HttpResponseRedirect(response)
                else:
                    return redirect('fir:list_firs_police_station')
            else:
                return redirect('fault', fault='Input parameters of Update FIR Form are not valid')
        else:
            form = forms.UpdateFIRPoliceStationForm(instance=models.FIR.objects.get(pk__exact=pk))
            return render(request, 'fir/update_fir_police_station.html', {'form':form})
    else:
        return redirect('fault', fault='ACCESS DENIED!')


@login_required
def update_fir_vrk_view(request, pk, sub_division_pk, police_station_pk):

    vrk_record_keepers = [u['user'] for u in acc_models.VRKRecordKeeper.objects.all().values('user')]

    prev_path = request.META.get('HTTP_REFERER', '/')
    current_path = request.path
    if prev_path == '/':
        response = '/'
        request.session['response_to_redirect'] = response
    elif not current_path in prev_path:
        response = prev_path
        request.session['response_to_redirect'] = response

    if request.user.pk in vrk_record_keepers:
        if request.method == 'POST':
            form = forms.UpdateFIRVRKForm(request.POST)
            if form.is_valid():
                fir = models.FIR.objects.get(pk__exact=pk)
                fir.ssp_approved = form.cleaned_data['ssp_approved']
                fir.save()
                response = request.session.get('response_to_redirect', None)
                if response and response != '/':
                    return HttpResponseRedirect(response)
                else:
                    return redirect('fir:list_firs_vrk_with_param', sub_division_pk = sub_division_pk, police_station_pk = police_station_pk)
            else:
                return redirect('fault', fault='Input parameters of Update FIR Form are not valid')
        else:
            form = forms.UpdateFIRVRKForm(instance=models.FIR.objects.get(pk__exact=pk))
            return render(request, 'fir/update_fir_vrk.html', {'form':form})
    else:
        return redirect('fault', fault='ACCESS DENIED!')


@login_required
def update_fir_ssp_view(request, pk, sub_division_pk, police_station_pk):

    ssp_record_keepers = [u['user'] for u in acc_models.SSPRecordKeeper.objects.all().values('user')]

    prev_path = request.META.get('HTTP_REFERER', '/')
    current_path = request.path
    if prev_path == '/':
        response = '/'
        request.session['response_to_redirect'] = response
    elif not current_path in prev_path:
        response = prev_path
        request.session['response_to_redirect'] = response

    if request.user.pk in ssp_record_keepers:
        if request.method == 'POST':
            form = forms.UpdateFIRSSPForm(request.POST)
            if form.is_valid():
                fir = models.FIR.objects.get(pk__exact=pk)
                fir.ssp_approved = form.cleaned_data['ssp_approved']
                fir.save()
                response = request.session.get('response_to_redirect', None)
                if response and response != '/':
                    return HttpResponseRedirect(response)
                else:
                    return redirect('fir:list_firs_ssp_with_param', sub_division_pk = sub_division_pk, police_station_pk = police_station_pk)
            else:
                return redirect('fault', fault='Input parameters of Update FIR Form are not valid')
        else:
            form = forms.UpdateFIRSSPForm(instance=models.FIR.objects.get(pk__exact=pk))
            return render(request, 'fir/update_fir_ssp.html', {'form':form})
    else:
        return redirect('fault', fault='ACCESS DENIED!')


@login_required
def update_fir_court_view(request, pk):

    court_record_keepers = [u['user'] for u in acc_models.CourtRecordKeeper.objects.all().values('user')]

    prev_path = request.META.get('HTTP_REFERER', '/')
    current_path = request.path
    if prev_path == '/':
        response = '/'
        request.session['response_to_redirect'] = response
    elif not current_path in prev_path:
        response = prev_path

fir/templates/fir/_location_form.html
{% load widget_tweaks %}

<form method='POST' id='location_form' class="center" data-police-stations-url="{% url 'fir:load_police_stations' %}">
    {% csrf_token %}

    <div class="row">
        <div class="input-field col s6 offset-s3">
            {{form.sub_division}}
            <label for="Sub Division">Sub Division</label>
        </div>
    </div>

    <div class="row">
        <div class="col s3 offset-s2">
            <label for="Police Station">Police Station</label>
        </div>
        <br><br>
        <div class="col s6 offset-s3 police_station_dropdown" style="border-bottom: 1px solid black;">
            {{form.police_station|add_class:'browser-default  indigo lighten-5'}}
        </div>
    </div>

    <button class="btn waves-effect waves-light" type="submit">
     Submit <i class="material-icons right">send</i>
    </button>

</form>

<script>
    $("#id_sub_division").change(function(){
        var url = $("#location_form").attr("data-police-stations-url");
        var sub_division_pk =  $(this).val();

        $.ajax({
            url: url,
            data: {
                'sub_division': sub_division_pk
            },
            success: function(data){
                $("#id_police_station").html(data);
            }
        });       
    });
</script>

fir/templates/fir/create_fir.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <br>
    <form method='POST' class='center'>

        {% csrf_token %}

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.fir_no}}
                <label for="FIR No">FIR No.</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.date_created|add_class:'datepicker'}}
                <label for="Date of Registration">Date of Registration</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.io_name}}
                <label for="Investigating Officer">Investigating Officer</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.accused_name|add_class:'materialize-textarea'}}
                <label for="Accused Name">Accused Name</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.under_section}}
                <label for="Under Section">Under Section</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.accused_status}}
                <label for="Accused Status">Accused Status</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.limitation_period}}
                <label for="Limitation Period">Limitation Period</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.current_status}}
                <label for="Current Status">Current Status</label>
            </div>
        </div>

        <button class="btn waves-effect waves-light" type="submit">
         Submit <i class="material-icons right">send</i>
        </button>
    </form>
    <br><br><br><br>
{% endblock content %}

fir/templates/fir/list_firs_court.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load templatetag %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list_css_temp.css' %}">
{% endblock %}

{% block content %}
    {% comment %} 
        <br>
        {% include 'fir/_location_form.html' %}
    {% endcomment %}
    <br><br>
    {% include 'fir/_firs_list.html' %}
{% endblock content %}

fir/templates/fir/list_firs_dsp.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load templatetag %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list_css_temp.css' %}">
{% endblock %}

{% block content %}
    <br>
    {% include 'fir/_ps_location_form.html' %}
    <br><br>
    {% include 'fir/_firs_list.html' %}
{% endblock content %}

fir/templates/fir/list_firs_police_station.html
{% extends 'base.html' %} 
{% load static %} 
{% load widget_tweaks %} 
{% load templatetag %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list_css_temp.css' %}">
{% endblock %}

{% block content %}
    {% include 'fir/_firs_list.html' %}
{% endblock content %}

fir/templates/fir/list_firs_ssp.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load templatetag %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list_css_temp.css' %}">
{% endblock %}

{% block content %}
    <br>
    {% include 'fir/_location_form.html' %}
    <br><br>
    {% include 'fir/_firs_list.html' %}

{% endblock content %}

fir/templates/fir/list_firs_vrk.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load templatetag %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list_css_temp.css' %}">
{% endblock %}

{% block content %}
    <br>
    {% include 'fir/_location_form.html' %}
    <br><br>
    {% include 'fir/_firs_list.html' %}

{% endblock content %}

fir/templates/fir/update_fir_court.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <form method='POST' class="center">

        {% csrf_token %}

        <div class="row">
            <div class="input-field col s6 offset-s3"> 
                <label for="id_received_in_court">
                    {{form.received_in_court}}
                    <span>Received in the court</span>
                </label>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.received_in_court_date|add_class:'datepicker'}}
                <label for="Date of receiving in the Court">Date of receiving in the Court</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.court_status}}
                <label for="Court Status">Court Status</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.reverted_by_court_date|add_class:'datepicker'}}
                <label for="Date of reverting by the Court">Date of reverting by the Court</label>
            </div>
        </div>

        <button class="btn waves-effect waves-light" type="submit">
         Submit <i class="material-icons right">send</i>
        </button>
        
    </form>
    <br><br><br><br>
{% endblock content %}

fir/templates/fir/update_fir_police_station.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <form method='POST' class='center'>
        {% csrf_token %}

        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.io_name}}
                <label for="Investigating Officer">Investigating Officer</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.accused_name|add_class:'materialize-textarea'}}
                <label for="Accused Name">Accused Name</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.under_section}}
                <label for="Under Section">Under Section</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.accused_status}}
                <label for="Accused Status">Accused Status</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.limitation_period}}
                <label for="Limitation Period">Limitation Period</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.current_status}}
                <label for="Current Status">Current Status</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3"> 
                <label for="id_put_in_ssp_office">
                    {{form.put_in_ssp_office}}
                    <span>Submitted in SSP Office</span>
                </label>
            </div>
        </div>
        <br><br>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.put_in_ssp_office_date|add_class:'datepicker'}}
                <label for="Date of submission to the SSP Office">Date of submission to the SSP Office</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3"> 
                <label for="id_put_in_court">
                    {{form.put_in_court}}
                    <span>Submitted in Court</span>
                </label>
            </div>
        </div>
        <br><br>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.put_in_court_date|add_class:'datepicker'}}
                <label for="Date of submission to the Court">Date of submission to the Court</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.received_from_court_date|add_class:'datepicker'}}
                <label for="Date of Receiving in Police Station">Date of Receiving in Police Station</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.appointed_io}}
                <label for="Appointed Investigating Officer">Appointed Investigating Officer for Re-investigation</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6 offset-s3"> 
                <label for="id_is_closed">
                    {{form.is_closed}}
                    <span>FIR Closed</span>
                </label>
            </div>
        </div>
        <br><br>
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{form.closed_date|add_class:'datepicker'}}
                <label for="Date of Closing of the FIR">Date of Closing of the FIR</label>
            </div>
        </div>
        <br><br>

        <button class="btn waves-effect waves-light" type="submit">
         Submit <i class="material-icons right">send</i>
        </button>
    </form>
    <br><br><br><br>
{% endblock content %}

fir/templates/fir/update_fir_ssp.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <form method='POST' class="center">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s3 offset-s5"> 
                <label for="id_ssp_approved">
                    {{form.ssp_approved}}
                    <span>Approved at SSP Office</span>
                </label>
            </div>
        </div>
        <br><br>
         <button class="btn waves-effect waves-light" type="submit">
         Submit <i class="material-icons right">send</i>
        </button>
    </form>
    <br><br><br><br>
{% endblock content %}

fir/templates/fir/update_fir_vrk.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <form method='POST' class="center">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s3 offset-s5"> 
                <label for="id_ssp_approved">
                    {{form.ssp_approved}}
                    <span>Approved at SSP Office</span>
                </label>
            </div>
        </div>
        <br><br>
         <button class="btn waves-effect waves-light" type="submit">
         Submit <i class="material-icons right">send</i>
        </button>
    </form>
    <br><br><br><br>
{% endblock content %}