FIRMonitoringSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('fir/', include('fir.urls')),
    path('firBeta/', include('firBeta.urls')),
    path('fault/<str:fault>/', views.fault, name='fault'),
    path('success/<str:msg>/', views.success, name='success'),
    path('send_mails_for_the_day/', views.send_mails_for_the_day, name='send_mails_for_the_day'),
    # path('populate/', views.populate, name='populate'),
    # path('delete/', views.delete, name='delete'),
    # path('change_passwords/', views.change_passwords, name='change_passwords'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

fir/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'fir'

urlpatterns = [

    # Police Station
    path('create_fir/', views.create_fir_view, name='create_fir'),
    path('update_fir_ps/<int:pk>', views.update_fir_police_station_view, name='update_fir_police_station'),
    path('add_new_phase/<int:pk>', views.add_new_phase_view, name='add_new_phase'),
    path('list_firs_police_station/', views.list_firs_police_station_view, name='list_firs_police_station'),

    
    # Court
    # path('update_fir_court/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_court_view, name='update_fir_court'),
    path('update_fir_court/<int:pk>/', views.update_fir_court_view, name='update_fir_court'),
    path('list_firs_court/', views.list_firs_court_view, name='list_firs_court'),
    # path('list_firs_court/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_court_with_param_view, name='list_firs_court_with_param'),


    # DSP
    path('list_firs_dsp/', views.list_firs_dsp_view, name='list_firs_dsp'),


    # VRK
    path('update_fir_vrk/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_vrk_view, name='update_fir_vrk'),
    path('list_firs_vrk/', views.list_firs_vrk_view, name='list_firs_vrk'),
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('list_firs_vrk/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_vrk_with_param_view, name='list_firs_vrk_with_param'),


    # SSP
    path('update_fir_ssp/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_ssp_view, name='update_fir_ssp'),
    path('list_firs_ssp/', views.list_firs_ssp_view, name='list_firs_ssp'),
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('list_firs_ssp/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_ssp_with_param_view, name='list_firs_ssp_with_param'),

    # Monitoring
    path('', views.filter_data_view, name='filter_fir_data'),
    path('detail/<int:pk>', views.detail_fir_view, name='detail_fir'),
]

firBeta/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'firBeta'

urlpatterns = [
    path('create/', views.create_fir, name='create'),
    path('ajax/create_fir_save/', views.create_fir_save_ajax_view, name='create_fir_save_ajax'),
    path('ajax/create_fir_save_add/', views.create_fir_save_add_ajax_view, name='create_fir_save_add_ajax'),
    path('ajax/create_fir_save_edit/', views.create_fir_save_edit_ajax_view, name='create_fir_save_edit_ajax'),
    path('ajax/create_fir_save_close/', views.create_fir_save_close_ajax_view, name='create_fir_save_close_ajax'),
    path('ps/filter/', views.filter_fir_ps_view, name='filter_fir_ps'),
    path('ps/filter/<int:asc>/', views.filter_fir_ps_view, name='filter_fir_ps_asc'),
    
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('ajax/all_fields_filled/', views.all_fields_filled_view, name='all_fields_filled'),

    path('vrk/', views.list_edit_fir_vrk_view, name='list_edit_fir_vrk'),
    path('vrk/<int:asc>/', views.list_edit_fir_vrk_view, name='list_edit_fir_vrk_asc'),
    path('ajax/edit_fir_save_vrk/', views.edit_fir_save_vrk_ajax_view, name='edit_fir_save_vrk_ajax'),
    path('vrk/filter/', views.filter_fir_vrk_view, name='filter_fir_vrk'),
    path('vrk/filter/<int:asc>/', views.filter_fir_vrk_view, name='filter_fir_vrk_asc'),

    path('ps/', views.list_edit_fir_ps_view, name='list_edit_fir_ps'),
    path('ps/<int:asc>/', views.list_edit_fir_ps_view, name='list_edit_fir_ps_asc'),
    path('ajax/edit_fir_save_ps/', views.edit_fir_save_ps_ajax_view, name='edit_fir_save_ps_ajax'),
    path('ajax/edit_fir_save_close_ps/', views.edit_fir_save_close_ps_ajax_view, name='edit_fir_save_close_ps_ajax'),

    path('nc/', views.list_edit_fir_nc_view, name='list_edit_fir_nc'),
    path('nc/<int:asc>/', views.list_edit_fir_nc_view, name='list_edit_fir_nc_asc'),
    path('ajax/edit_fir_save_nc/', views.edit_fir_save_nc_ajax_view, name='edit_fir_save_nc_ajax'),
    path('ajax/edit_fir_save_close_nc/', views.edit_fir_save_close_nc_ajax_view, name='edit_fir_save_close_nc_ajax'),
    path('nc/filter/', views.filter_fir_nc_view, name='filter_fir_nc'),
    path('nc/filter/<int:asc>/', views.filter_fir_nc_view, name='filter_fir_nc_asc'),

    path('add-new-phase/<int:pk>/', views.add_new_phase_fir_view, name='add_new_phase_fir'),
    path('ajax/add_new_phase_fir_save/', views.add_new_phase_fir_save_ajax_view, name='add_new_phase_fir_save_ajax'),
    path('ajax/add_new_phase_fir_save_close/', views.add_new_phase_fir_save_close_ajax_view, name='add_new_phase_fir_save_close_ajax'),

    path('dsp/', views.list_fir_dsp_view, name='list_fir_dsp'),
    path('dsp/<int:asc>/', views.list_fir_dsp_view, name='list_fir_dsp_asc'),
    path('dsp/filter/', views.filter_fir_dsp_view, name='filter_fir_dsp'),
    path('dsp/filter/<int:asc>/', views.filter_fir_dsp_view, name='filter_fir_dsp_asc'),
    path('dsp/dashboard/', views.dashboard_dsp_view, name='dashboard_dsp'),

    path('ssp/', views.list_fir_ssp_view, name='list_fir_ssp'),
    path('ssp/<int:asc>/', views.list_fir_ssp_view, name='list_fir_ssp_asc'),
    path('ssp/filter/', views.filter_fir_ssp_view, name='filter_fir_ssp'),
    path('ssp/filter/<int:asc>/', views.filter_fir_ssp_view, name='filter_fir_ssp_asc'),
    path('ssp/dashboard/', views.dashboard_ssp_view, name='dashboard_ssp'),
]

firBeta/models.py
from django.db import models

# Create your models here.


class FIR(models.Model):

    sub_division = models.ForeignKey(
        "location.SubDivision", related_name='fir_list', on_delete=models.CASCADE)
    police_station = models.ForeignKey(
        "location.PoliceStation", related_name='fir_list', on_delete=models.CASCADE)

    fir_no = models.CharField(max_length=50)

    is_closed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.sub_division} - {self.police_station} - {self.fir_no}'

    class Meta():
        unique_together = ['sub_division', 'police_station', 'fir_no']
        ordering = ['sub_division', 'police_station', '-pk']
        verbose_name = 'FIR'
        verbose_name_plural = 'FIRs'


class FIRPhase(models.Model):

    PHASE_CHOICES = [(1, 1), (2, 2), (3, 3)]
    CURRENT_STATUS_CHOICES = [('Under Investigation','Under Investigation'),('Challan Filed','Challan Filed'),('Untraced','Untraced'),('Cancelled','Cancelled')]
    VRK_STATUS_CHOICES = [('Pending', 'Pending'),('Approved', 'Approved')]
    NC_STATUS_CHOICES = [('Pending', 'Pending'), ('Approved', 'Approved'), ('Reinvestigation', 'Reinvestigation')]

    fir = models.ForeignKey(
        "firBeta.FIR", related_name='phases', on_delete=models.CASCADE)
    phase_index = models.IntegerField(choices=PHASE_CHOICES)
    date_registered = models.DateField()
    date_created_on_system = models.DateField(auto_now_add=True)

    under_section = models.CharField(max_length=100)
    io_name = models.CharField(max_length=100)
    accused_name = models.TextField(blank=True, null=True)
    accused_status = models.TextField(blank=True, null=True)
    limitation_period = models.PositiveIntegerField()

    current_status = models.CharField(max_length=50, choices=CURRENT_STATUS_CHOICES)
    current_status_date = models.DateField(blank=True, null=True)

    vrk_receival_date = models.DateField(blank=True, null=True)
    vrk_status = models.CharField(max_length=50, choices=VRK_STATUS_CHOICES, blank=True, null=True)
    vrk_status_date = models.DateField(blank=True, null=True)
    vrk_sent_back_date = models.DateField(blank=True, null=True)

    received_from_vrk_date = models.DateField(blank=True, null=True)
    put_in_court_date = models.DateField(blank=True, null=True)

    nc_receival_date = models.DateField(blank=True, null=True)
    nc_status = models.CharField(max_length=50, choices=NC_STATUS_CHOICES, blank=True, null=True)
    nc_status_date = models.DateField(blank=True, null=True)
    nc_sent_back_date = models.DateField(blank=True, null=True)

    received_from_nc_date = models.DateField(blank=True, null=True)
    appointed_io = models.CharField(max_length=100, blank=True, null=True)
    appointed_io_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.fir.sub_division} - {self.fir.police_station} - {self.fir.fir_no} - {self.phase_index}'

    class Meta():
        unique_together = ['fir', 'phase_index']
        ordering = ['-fir__pk', 'phase_index']
        verbose_name = 'FIR Phase'
        verbose_name_plural = 'FIR Phases'


class LastMailDate(models.Model):
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.date}'

location/models.py
from django.db import models

# Create your models here.


class SubDivision(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class PoliceStation(models.Model):
    sub_division = models.ForeignKey("location.SubDivision", related_name='police_stations',on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    

firBeta/templates/firBeta/_dashboard_ssp_form.html
{% load widget_tweaks %}

<form method='POST' id='dashboard_form' class="center" data-police-stations-url="{% url 'firBeta:load_police_stations' %}" data-selected-sub-division='{{selected_sub_division}}' data-selected-police-station='{{selected_police_station}}'>
    {% csrf_token %}

    <div class="row">
        <div class="input-field col s6 offset-s3">
            {{form.sub_division}}
            <label for="Sub Division">Sub Division</label>
        </div>
    </div>

    <div class="row">
        <div class="col s3 offset-s2">
            <label for="Police Station">Police Station</label>
        </div>
        <br><br>
        <div class="col s6 offset-s3 police_station_dropdown" style="border-bottom: 1px solid black;">
            {{form.police_station|add_class:'browser-default  green lighten-5'}}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="input-field col s3 offset-s3">
            {{form.start_date|add_class:'datepicker'}}
            <label for="Start Date">Start Date</label>
        </div>
        <div class="input-field col s3">
            {{form.end_date|add_class:'datepicker'}}
            <label for="End Date">End Date</label>
        </div>
    </div>

    <button class="btn waves-effect waves-light" type="submit">
     Submit <i class="material-icons right">send</i>
    </button>

</form>

<script>

    $(document).ready(function(){
        var url = $("#dashboard_form").attr("data-police-stations-url");
        var selected_sub_division = $("#dashboard_form").attr("data-selected-sub-division");
        var selected_police_station = $("#dashboard_form").attr("data-selected-police-station");
        if(selected_sub_division) {
            var sub_division_pk =  selected_sub_division;

            $.ajax({
                url: url,
                data: {
                    'sub_division': sub_division_pk
                },
                success: function(data){
                    $("#id_police_station").html(data);
                    $('#id_sub_division').val(selected_sub_division); 
                    $('select').formSelect();
                    $('#id_police_station').val(selected_police_station);
                }
            });
        }
    });

    $("#id_sub_division").change(function(){
        var url = $("#dashboard_form").attr("data-police-stations-url");
        var sub_division_pk =  $(this).val();

        $.ajax({
            url: url,
            data: {
                'sub_division': sub_division_pk
            },
            success: function(data){
                $("#id_police_station").html(data);
            }
        });       
    });
</script>

firBeta/templates/firBeta/_filter_summary.html
{% if summary %}
    <div class="container">
        <div class="row">
            <div class="card horizontal green lighten-4 col s6">
                <div class="card-content center">
                    <p class="card-title"><strong>Aggregate</strong><br>FIRs Registered</p>
                    <p class="card-title">{{ summary.firs_registered_count }}</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>Aggregate</strong><br>FIRs Closed</p>
                    <p class="card-title">{{ summary.firs_closed_count }}</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>Status</strong><br>Under Investigation</p>
                    <p class="card-title">{{summary.firs_status_under_investigation_unique_count}} ({{summary.firs_status_under_investigation_count}})</p>
                </div>
            </div>
            <div class="col s1"></div>
            <div class="card horizontal green lighten-4 col s5">
                <div class="card-content center">
                    <p class="card-title"><strong>Status</strong><br>Untraced</p>
                    <p class="card-title">{{summary.firs_status_untraced_unique_count}} ({{summary.firs_status_untraced_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>Status</strong><br>Cancelled</p>
                    <p class="card-title">{{summary.firs_status_cancelled_unique_count}} ({{summary.firs_status_cancelled_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>Status</strong><br>Challan Filed</p>
                    <p class="card-title">{{summary.firs_status_challan_filed_count}}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="card horizontal green lighten-4 col s6">
                <div class="card-content center">
                    <p class="card-title"><strong>VRK</strong><br>Received</p>
                    <p class="card-title">{{summary.firs_vrk_received_unique_count}} ({{summary.firs_vrk_received_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>VRK</strong><br>Approved</p>
                    <p class="card-title">{{summary.firs_vrk_status_approved_unique_count}} ({{summary.firs_vrk_status_approved_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>VRK</strong><br>Sent Back</p>
                    <p class="card-title">{{summary.firs_vrk_sent_back_unique_count}} ({{summary.firs_vrk_sent_back_count}})</p>
                </div>
            </div>
            <div class="col s1"></div>
            <div class="card horizontal green lighten-4 col s5">
                <div class="card-content center">
                    <p class="card-title"><strong>PS</strong><br>Received from VRK</p>
                    <p class="card-title">{{ summary.firs_received_from_vrk_unique_count }} ({{summary.firs_received_from_vrk_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>PS</strong><br>Put in Court</p>
                    <p class="card-title">{{ summary.firs_put_in_court_unique_count }} ({{summary.firs_put_in_court_count}})</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="card horizontal green lighten-4 col s6">
                <div class="card-content center">
                    <p class="card-title"><strong>NC</strong><br>Received</p>
                    <p class="card-title">{{summary.firs_nc_receival_unique_count}} ({{summary.firs_nc_receival_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>NC</strong><br>Approved</p>
                    <p class="card-title">{{summary.firs_nc_status_approved_unique_count}} ({{summary.firs_nc_status_approved_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>NC</strong><br>Reinvestigation</p>
                    <p class="card-title">{{summary.firs_nc_status_reinvestigation_unique_count}} ({{summary.firs_nc_status_reinvestigation_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>NC</strong><br>SentBack</p>
                    <p class="card-title">{{summary.firs_nc_sent_back_unique_count}} ({{summary.firs_nc_sent_back_count}})</p>
                </div>
            </div>
            <div class="col s1"></div>
            <div class="card horizontal green lighten-4 col s5">
                <div class="card-content center">
                    <p class="card-title"><strong>PS</strong><br>Received from NC</p>
                    <p class="card-title">{{ summary.firs_received_from_nc_unique_count }} ({{summary.firs_received_from_nc_count}})</p>
                </div>
                <div class="card-content center">
                    <p class="card-title"><strong>PS</strong><br>Marked to IO</p>
                    <p class="card-title">{{ summary.firs_appointed_io_unique_count }} ({{summary.firs_appointed_io_count}})</p>
                </div>
            </div>
        </div>
    </div>
{% endif %}

firBeta/templates/firBeta/_location_form.html
{% load widget_tweaks %}

<form method='GET' id='location_form' class="center" data-police-stations-url="{% url 'firBeta:load_police_stations' %}" data-selected-sub-division='{{selected_sub_division}}' data-selected-police-station='{{selected_police_station}}'>
    {% csrf_token %}

    <div class="row">
        <div class="input-field col s6 offset-s3">
            {{form.sub_division}}
            <label for="Sub Division">Sub Division</label>
        </div>
    </div>

    <div class="row">
        <div class="col s3 offset-s2">
            <label for="Police Station">Police Station</label>
        </div>
        <br><br>
        <div class="col s6 offset-s3 police_station_dropdown" style="border-bottom: 1px solid black;">
            {{form.police_station|add_class:'browser-default  green lighten-5'}}
        </div>
    </div>

    <button class="btn waves-effect waves-light" type="submit">
     Submit <i class="material-icons right">send</i>
    </button>

</form>

<script>
    $(document).ready(function(){
        var url = $("#location_form").attr("data-police-stations-url");
        var selected_sub_division = $("#location_form").attr("data-selected-sub-division");
        var selected_police_station = $("#location_form").attr("data-selected-police-station");
        if(selected_sub_division) {
            var sub_division_pk =  selected_sub_division;

            $.ajax({
                url: url,
                data: {
                    'sub_division': sub_division_pk
                },
                success: function(data){
                    $("#id_police_station").html(data);
                    $('#id_sub_division').val(selected_sub_division); 
                    $('select').formSelect();
                    $('#id_police_station').val(selected_police_station);
                }
            });
        }
    });


    $("#id_sub_division").change(function(){
        var url = $("#location_form").attr("data-police-stations-url");
        var sub_division_pk =  $(this).val();

        $.ajax({
            url: url,
            data: {
                'sub_division': sub_division_pk
            },
            success: function(data){
                $("#id_police_station").html(data);
            }
        });       
    });
</script>

firBeta/templates/firBeta/dashboard_dsp.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load templatetag_beta %}

{% block head %}
<style>
    .container {
        margin: 0 auto;
        max-width: 1280px;
        width: 90%;
    }
</style>
{% endblock head %}

{% block content %}
<br>
{% include 'firBeta/_dashboard_dsp_form.html' %}
<br><br>

<div class="container">
    <div class="row">
        <div class="card horizontal green lighten-4 col s6">
            <div class="card-content center">
                <p class="card-title"><strong>Aggregate</strong><br>FIRs Registered</p>
                <p class="card-title">{{ firs_registered_count }}</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>Aggregate</strong><br>FIRs Closed</p>
                <p class="card-title">{{ firs_closed_count }}</p>
            </div>
        </div>
        <div class="col s1"></div>
        <div class="card horizontal green lighten-4 col s5">
            <div class="card-content center">
                <p class="card-title"><strong>Status</strong><br>Untraced</p>
                <p class="card-title">{{firs_status_untraced_unique_count}} ({{firs_status_untraced_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>Status</strong><br>Cancelled</p>
                <p class="card-title">{{firs_status_cancelled_unique_count}} ({{firs_status_cancelled_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>Status</strong><br>Challan Filed</p>
                <p class="card-title">{{firs_status_challan_filed_count}}</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card horizontal green lighten-4 col s6">
            <div class="card-content center">
                <p class="card-title"><strong>VRK</strong><br>Received</p>
                <p class="card-title">{{firs_vrk_received_unique_count}} ({{firs_vrk_received_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>VRK</strong><br>Approved</p>
                <p class="card-title">{{firs_vrk_status_approved_unique_count}} ({{firs_vrk_status_approved_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>VRK</strong><br>Sent Back</p>
                <p class="card-title">{{firs_vrk_sent_back_unique_count}} ({{firs_vrk_sent_back_count}})</p>
            </div>
        </div>
        <div class="col s1"></div>
        <div class="card horizontal green lighten-4 col s5">
            <div class="card-content center">
                <p class="card-title"><strong>PS</strong><br>Received from VRK</p>
                <p class="card-title">{{ firs_received_from_vrk_unique_count }} ({{firs_received_from_vrk_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>PS</strong><br>Put in Court</p>
                <p class="card-title">{{ firs_put_in_court_unique_count }} ({{firs_put_in_court_count}})</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card horizontal green lighten-4 col s6">
            <div class="card-content center">
                <p class="card-title"><strong>NC</strong><br>Received</p>
                <p class="card-title">{{firs_nc_receival_unique_count}} ({{firs_nc_receival_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>NC</strong><br>Approved</p>
                <p class="card-title">{{firs_nc_status_approved_unique_count}} ({{firs_nc_status_approved_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>NC</strong><br>Reinvestigation</p>
                <p class="card-title">{{firs_nc_status_reinvestigation_unique_count}} ({{firs_nc_status_reinvestigation_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>NC</strong><br>SentBack</p>
                <p class="card-title">{{firs_nc_sent_back_unique_count}} ({{firs_nc_sent_back_count}})</p>
            </div>
        </div>
        <div class="col s1"></div>
        <div class="card horizontal green lighten-4 col s5">
            <div class="card-content center">
                <p class="card-title"><strong>PS</strong><br>Received from NC</p>
                <p class="card-title">{{ firs_received_from_nc_unique_count }} ({{firs_received_from_nc_count}})</p>
            </div>
            <div class="card-content center">
                <p class="card-title"><strong>PS</strong><br>Marked to IO</p>
                <p class="card-title">{{ firs_appointed_io_unique_count }} ({{firs_appointed_io_count}})</p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block tail %}
{% endblock tail %}

firBeta/templates/firBeta/load_police_stations.html
<option value="">---Select---</option>
<option value="all">All</option>
{% for police_station in police_station_list %}
<option value="{{ police_station.pk }}">{{ police_station.name }}</option>
{% endfor %}