FIRMonitoringSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('fir/', include('fir.urls')),
    path('firBeta/', include('firBeta.urls')),
    path('fault/<str:fault>/', views.fault, name='fault'),
    path('success/<str:msg>/', views.success, name='success'),
    path('send_mails_for_the_day/', views.send_mails_for_the_day, name='send_mails_for_the_day'),
    # path('populate/', views.populate, name='populate'),
    # path('delete/', views.delete, name='delete'),
    # path('change_passwords/', views.change_passwords, name='change_passwords'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

account/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

fir/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'fir'

urlpatterns = [

    # Police Station
    path('create_fir/', views.create_fir_view, name='create_fir'),
    path('update_fir_ps/<int:pk>', views.update_fir_police_station_view, name='update_fir_police_station'),
    path('add_new_phase/<int:pk>', views.add_new_phase_view, name='add_new_phase'),
    path('list_firs_police_station/', views.list_firs_police_station_view, name='list_firs_police_station'),

    
    # Court
    # path('update_fir_court/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_court_view, name='update_fir_court'),
    path('update_fir_court/<int:pk>/', views.update_fir_court_view, name='update_fir_court'),
    path('list_firs_court/', views.list_firs_court_view, name='list_firs_court'),
    # path('list_firs_court/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_court_with_param_view, name='list_firs_court_with_param'),


    # DSP
    path('list_firs_dsp/', views.list_firs_dsp_view, name='list_firs_dsp'),


    # VRK
    path('update_fir_vrk/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_vrk_view, name='update_fir_vrk'),
    path('list_firs_vrk/', views.list_firs_vrk_view, name='list_firs_vrk'),
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('list_firs_vrk/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_vrk_with_param_view, name='list_firs_vrk_with_param'),


    # SSP
    path('update_fir_ssp/<int:pk>/<int:sub_division_pk>/<int:police_station_pk>', views.update_fir_ssp_view, name='update_fir_ssp'),
    path('list_firs_ssp/', views.list_firs_ssp_view, name='list_firs_ssp'),
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('list_firs_ssp/<int:sub_division_pk>/<int:police_station_pk>', views.list_firs_ssp_with_param_view, name='list_firs_ssp_with_param'),

    # Monitoring
    path('', views.filter_data_view, name='filter_fir_data'),
    path('detail/<int:pk>', views.detail_fir_view, name='detail_fir'),
]

firBeta/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'firBeta'

urlpatterns = [
    path('create/', views.create_fir, name='create'),
    path('ajax/create_fir_save/', views.create_fir_save_ajax_view, name='create_fir_save_ajax'),
    path('ajax/create_fir_save_add/', views.create_fir_save_add_ajax_view, name='create_fir_save_add_ajax'),
    path('ajax/create_fir_save_edit/', views.create_fir_save_edit_ajax_view, name='create_fir_save_edit_ajax'),
    path('ajax/create_fir_save_close/', views.create_fir_save_close_ajax_view, name='create_fir_save_close_ajax'),
    path('ps/filter/', views.filter_fir_ps_view, name='filter_fir_ps'),
    path('ps/filter/<int:asc>/', views.filter_fir_ps_view, name='filter_fir_ps_asc'),
    
    path('ajax/load_ps/', views.load_police_stations_view, name='load_police_stations'),
    path('ajax/all_fields_filled/', views.all_fields_filled_view, name='all_fields_filled'),

    path('vrk/', views.list_edit_fir_vrk_view, name='list_edit_fir_vrk'),
    path('vrk/<int:asc>/', views.list_edit_fir_vrk_view, name='list_edit_fir_vrk_asc'),
    path('ajax/edit_fir_save_vrk/', views.edit_fir_save_vrk_ajax_view, name='edit_fir_save_vrk_ajax'),
    path('vrk/filter/', views.filter_fir_vrk_view, name='filter_fir_vrk'),
    path('vrk/filter/<int:asc>/', views.filter_fir_vrk_view, name='filter_fir_vrk_asc'),

    path('ps/', views.list_edit_fir_ps_view, name='list_edit_fir_ps'),
    path('ps/<int:asc>/', views.list_edit_fir_ps_view, name='list_edit_fir_ps_asc'),
    path('ajax/edit_fir_save_ps/', views.edit_fir_save_ps_ajax_view, name='edit_fir_save_ps_ajax'),
    path('ajax/edit_fir_save_close_ps/', views.edit_fir_save_close_ps_ajax_view, name='edit_fir_save_close_ps_ajax'),

    path('nc/', views.list_edit_fir_nc_view, name='list_edit_fir_nc'),
    path('nc/<int:asc>/', views.list_edit_fir_nc_view, name='list_edit_fir_nc_asc'),
    path('ajax/edit_fir_save_nc/', views.edit_fir_save_nc_ajax_view, name='edit_fir_save_nc_ajax'),
    path('ajax/edit_fir_save_close_nc/', views.edit_fir_save_close_nc_ajax_view, name='edit_fir_save_close_nc_ajax'),
    path('nc/filter/', views.filter_fir_nc_view, name='filter_fir_nc'),
    path('nc/filter/<int:asc>/', views.filter_fir_nc_view, name='filter_fir_nc_asc'),

    path('add-new-phase/<int:pk>/', views.add_new_phase_fir_view, name='add_new_phase_fir'),
    path('ajax/add_new_phase_fir_save/', views.add_new_phase_fir_save_ajax_view, name='add_new_phase_fir_save_ajax'),
    path('ajax/add_new_phase_fir_save_close/', views.add_new_phase_fir_save_close_ajax_view, name='add_new_phase_fir_save_close_ajax'),

    path('dsp/', views.list_fir_dsp_view, name='list_fir_dsp'),
    path('dsp/<int:asc>/', views.list_fir_dsp_view, name='list_fir_dsp_asc'),
    path('dsp/filter/', views.filter_fir_dsp_view, name='filter_fir_dsp'),
    path('dsp/filter/<int:asc>/', views.filter_fir_dsp_view, name='filter_fir_dsp_asc'),
    path('dsp/dashboard/', views.dashboard_dsp_view, name='dashboard_dsp'),

    path('ssp/', views.list_fir_ssp_view, name='list_fir_ssp'),
    path('ssp/<int:asc>/', views.list_fir_ssp_view, name='list_fir_ssp_asc'),
    path('ssp/filter/', views.filter_fir_ssp_view, name='filter_fir_ssp'),
    path('ssp/filter/<int:asc>/', views.filter_fir_ssp_view, name='filter_fir_ssp_asc'),
    path('ssp/dashboard/', views.dashboard_ssp_view, name='dashboard_ssp'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FIR Monitoring System</title>


    <!-- Compiled and minified jQuery -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script> -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

    <!-- Materialize Compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">

    <!-- Materialize Icons -->
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'materialize/css/icon.css' %}">

    <!-- Materialize Compiled and minified JavaScript -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
    <script src="{% static 'materialize/js/materialize.min.js' %}"></script>

    <!-- Floating Scrollbar minified CSS and JavaScript -->
    <link rel="stylesheet" href="{% static 'floating_scroll/floating_scroll_css.css' %}">
    <script src="{% static 'floating_scroll/floating_scroll_js.js' %}"></script>

    <style>
        body{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif !important;
        }


        ::-webkit-scrollbar {
        width: 5px !important;
        }

        ::-webkit-scrollbar-track {
        background: #e8f5e9 ;
        }

        ::-webkit-scrollbar-thumb {
        background: #006064;
        }

        ::-webkit-scrollbar-thumb:hover {
        background: #009688;
        }


    </style>

    {% block head %} 
    {% endblock head %}
</head>

<body class="green lighten-5">
    {% block nav %} 
    {% endblock nav %}

    <div class="navbar-fixed">
        <nav>
            <!-- <div class="nav-wrapper indigo darken-1"> -->
            <div class="nav-wrapper cyan darken-4">
                <a href="#!" class="left brand-logo">&nbsp;FIR Tracking System</a>
                <ul class="right hide-on-med-and-down">
                    {% if user.is_authenticated %}
                        {% if user.pk in police_station_record_keepers %}
                            <li><a href="{% url 'firBeta:create' %}" class="teal-text text-lighten-5">Register FIR</a></li>
                            <li><a href="{% url 'firBeta:list_edit_fir_ps'%}" class="teal-text text-lighten-5">View FIRs</a></li>
                            <li><a href="{% url 'firBeta:filter_fir_ps' %}" class="teal-text text-lighten-5">Search/Filters</a></li>
                        {% endif %}
                        {% if user.pk in court_record_keepers %}
                            <li><a href="{% url 'firBeta:list_edit_fir_nc' %}" class="teal-text text-lighten-5">View FIRs</a></li>
                            <li><a href="{% url 'firBeta:filter_fir_nc' %}" class="teal-text text-lighten-5">Search/Filters</a></li>
                        {% endif %}
                        {% if user.pk in dsp_record_keepers %}
                            <li><a href="{% url 'firBeta:list_fir_dsp' %}" class="teal-text text-lighten-5">View FIRs</a></li>
                            <li><a href="{% url 'firBeta:filter_fir_dsp' %}" class="teal-text text-lighten-5">Search/Filters</a></li>
                            <li><a href="{% url 'firBeta:dashboard_dsp' %}" class="teal-text text-lighten-5">Stats</a></li>
                        {% endif %}
                        {% if user.pk in vrk_record_keepers %}
                            <li><a href="{% url 'firBeta:list_edit_fir_vrk' %}" class="teal-text text-lighten-5">View FIRs</a></li>
                            <li><a href="{% url 'firBeta:filter_fir_vrk' %}" class="teal-text text-lighten-5">Search/Filters</a></li>
                        {% endif %}
                        {% if user.pk in ssp_record_keepers %}
                            <li><a href="{% url 'firBeta:list_fir_ssp' %}" class="teal-text text-lighten-5">View FIRs</a></li>
                            <li><a href="{% url 'firBeta:filter_fir_ssp' %}" class="teal-text text-lighten-5">Search/Filters</a></li>
                            <li><a href="{% url 'firBeta:dashboard_ssp' %}" class="teal-text text-lighten-5">Stats</a></li>
                        {% endif %}
                        <!-- <li><a href="{% url 'fir:filter_fir_data' %}" class="teal-text text-lighten-5">Search FIRs</a></li> -->
                        <li style="border-left: #004d40 5px solid;"><a href="{% url 'account:logout' %}">Logout&nbsp;</a></li>
                    {% else %}
                        <li><a href="{% url 'account:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    <div class="hide-on-med-and-down">
        {% block content %} 
        {% endblock content %}
    </div>

    <div class="hide-on-large-only">
        <h4 class="center">The Tracking System is a Desktop only software. Kindly use it on a screen size of >992px</h4>
    </div>

    {% block tail %} 
    {% endblock tail %}

    <script>
        $(document).ready(function(){
            $('select').formSelect();
        });

        $(document).ready(function(){
            $('.datepicker').datepicker({
                format:'dd/mm/yy',
                maxDate: new Date()
            });
        });

        $(document).ready(function () {
            $('.modal').modal();
        });
    </script>


</body>

</html>

templates/fault.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <br><br><br>
        <div class="row">
            <div class="col s3 m3 l3"></div>
            <div class="col s6 m6 l6">
                <div class="card blue-grey lighten-4 center">
                    <div class="card-content">
                        <span class="card-title"><b>Error Encountered</b></span>
                        <p>{{fault}}</p>
                    </div>
                </div>
            </div>
            <div class="col s3 m3 l3"></div>
        </div>
    </div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Welcome to the home page</h1>
    <h3>Your content goes here</h3>
{% endblock content %}

templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <br><br><br>
        <div class="row">
            <div class="col s3 m3 l3"></div>
            <div class="col s6 m6 l6">
                <div class="card green lighten-4 center">
                    <div class="card-content">
                        <span class="card-title"><b>Task Executed Successfully</b></span>
                        <p>{{msg}}</p>
                    </div>
                </div>
            </div>
            <div class="col s3 m3 l3"></div>
        </div>
    </div>
{% endblock content %}